services:
  train_container:
    container_name: llava
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/root/workspace
      - ./.vscode:/root/.vscode
      - ~/.cache:/root/.cache
      - ~/output_dir:/root/output_dir
    tty: true
    shm_size: 126G
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - TZ=Asia/Seoul
    cap_drop:
      - SYS_ADMIN
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]